---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ZeroEst

<!-- badges: start -->
<!-- badges: end -->

The goal of ZeroEst is to provide set of functions to estimate the noise level in a semi-supervised high dimensional regression model.

## Installation


You can install from from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Ilanlivne/ZeroEst")
```
## Example

This is a basic example which shows you how to calculate the naive and proposed estimator:

```{r example}
library(ZeroEst)
## basic example code
n = 100
p = n
c = 10       #number of large betas
large = 5
small = 0.05
beta_range <- c(rep(small,p-c),rep(large, c) )
sigma2<- 1
X <- matrix(rnorm(n*p) ,nrow = n, ncol = p)
Y <- X %*% beta_range + rnorm(n, mean=0, sd=sqrt(sigma2))  # basic model
naive(X,Y)
#> 270.4212
proposed_estimator(X,Y)
#> 90.71639
```

