// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// func
double func(DoubleVector vec1, DoubleVector vec2, DoubleVector vec3);
RcppExport SEXP _ZeroEst_func(SEXP vec1SEXP, SEXP vec2SEXP, SEXP vec3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type vec1(vec1SEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type vec2(vec2SEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type vec3(vec3SEXP);
    rcpp_result_gen = Rcpp::wrap(func(vec1, vec2, vec3));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ZeroEst_func", (DL_FUNC) &_ZeroEst_func, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ZeroEst(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
