# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

func <- function(vec1, vec2, vec3) {
    .Call('_ZeroEst_func', PACKAGE = 'ZeroEst', vec1, vec2, vec3)
}

